ever-co/ever-traduora

deploy/k8s/traduora-preview-ingress-gcp.yaml
deploy/k8s/traduora-preview-ingress-nginx.yaml

Fix typo in Kubernetes label

---

README.md
api/package.json
api/src/controllers/exports.controller.ts
api/src/controllers/import.controller.ts
api/src/domain/http.ts
api/src/formatters/fixtures/index.ts
api/src/formatters/fixtures/simple.po
api/src/formatters/gettext.spec.ts
api/src/formatters/gettext.ts
api/yarn.lock
docs/concepts/formats.md
webapp/src/app/projects/models/export.ts
webapp/src/app/projects/models/import.ts

Add support for gettext file formats on import and export.

Add support for gettext (po)

---

README.md

fixed available

---

api/src/filters/exception.filter.ts
api/src/services/user.service.ts
api/test/user.e2e-spec.ts
docs/changelog.md
webapp/src/app/auth/stores/auth.state.ts
webapp/src/app/shared/util/api-error.ts

Add guard against account deletion when is last project admin of project with team

Account deletion protection

---

api/src/controllers/exports.controller.ts
api/src/controllers/term.controller.ts
api/test/export.e2e-spec.ts
api/test/term.e2e-spec.ts
docs/changelog.md

Use lexical order for terms on export and find all endpoint
Fixes #21

Lexical order of terms

---

webapp/src/app/shared/components/search/search.component.ts

It was not possible to search for terms which included uppercase letters.
2. Please check our [contribution guidelines](https://docs.traduora.com/docs/contributing#review-process-for-this-repo) for some help in the process.

fixed term search

---

.circleci/config.yml
api/package.json
api/src/config.ts
api/src/main.ts
api/test/import.e2e-spec.ts
api/test/project.e2e-spec.ts
api/test/util.ts
bin/check.sh
bin/test.sh
docs/deployment.md

Fixes end to end test randomly failing on ECONNRESET error.

Fix e2e tests

---

webapp/src/app/shared/components/app-bar/app-bar.component.html

Fixes a little positioning flaw when the account dropdown menu is not fully in the viewport

Fix positioning of account dropdown menu

---

api/src/formatters/fixtures/simple-context.po
api/src/formatters/gettext.spec.ts
api/src/formatters/gettext.ts
docs/changelog.md

Fix gettext context parsing

---

api/src/config.ts
api/src/formatters/jsonnested.spec.ts
api/src/formatters/jsonnested.ts
api/src/formatters/yaml-nested.ts
docs/changelog.md
docs/configuration.md

Increase max json levels

---

api/src/formatters/fixtures/simple-flat.json
api/src/formatters/fixtures/simple-nested.json
api/src/formatters/jsonflat.ts
api/src/formatters/jsonnested.ts
docs/changelog.md

Pretty print json

---

api/src/formatters/fixtures/function-name-flat.json
api/src/formatters/fixtures/function-name-nested.json
api/src/formatters/jsonnested.spec.ts

Json nested export tests

---

api/src/config.ts
docker-compose.yaml
docs/configuration.md
docs/deployment.md

For https://github.com/ever-co/ever-traduora/issues/75
Simple change to make the type as a variable

Make the DB type as variable

---

api/package.json
api/src/controllers/exports.controller.ts
api/src/domain/http.ts
webapp/src/app/projects/components/export-locale/export-locale.component.html
webapp/src/app/projects/components/export-locale/export-locale.component.ts
webapp/src/app/projects/services/export.service.ts

2. Please check our [contribution guidelines](https://docs.traduora.co/docs/contributing#review-process-for-this-repo) for some help in the process.

feat(fallback-locale): add fallback locale on export

---

.circleci/config.yml

2. Please check our [contribution guidelines](https://docs.traduora.co/docs/contributing#review-process-for-this-repo) for some help in the process.

feat: release

---

api/src/controllers/project-stats.controller.ts

This change resolves #386 by changing the rounding to down

fix: change translation progress rounding to down

---

api/package.json
webapp/package.json
yarn.lock

2. Please check our [contribution guidelines](https://docs.traduora.co/docs/contributing#review-process-for-this-repo) for some help in the process.

chore(deps): remove unnecessary crypto dependency

---

webapp/src/app/auth/components/forgot-password/forgot-password.component.ts
webapp/src/app/auth/components/login/login.component.ts
webapp/src/app/auth/components/reset-password/reset-password.component.ts
webapp/src/app/auth/components/signup/signup.component.ts
webapp/src/app/auth/components/user-settings/user-settings.component.ts
webapp/src/app/projects/components/add-api-client/add-api-client.component.ts
webapp/src/app/projects/components/add-team-member/add-team-member.component.ts
webapp/src/app/projects/components/edit-label/edit-label.component.ts
webapp/src/app/projects/components/new-label/new-label.component.ts
webapp/src/app/projects/components/new-project/new-project.component.ts
webapp/src/app/projects/components/new-term/new-term.component.ts
webapp/src/app/projects/components/project-settings/project-settings.component.ts

2. Please check our [contribution guidelines](https://docs.traduora.co/docs/contributing#review-process-for-this-repo) for some help in the process.

Refactor: Replace UntypedFormBuilder with FormBuilder

---

api/package.json
bin/build.sh
webapp/package.json

1.  Contributor license agreement
2.  Please check our [contribution guidelines](https://docs.traduora.co/docs/contributing#review-process-for-this-repo) for some help in the process.

chore: production build

---

api/package.json
docs-website/package.json
docs-website/static/docs/api/v1/swagger.json
package.json
webapp/package.json

1.  Contributor license agreement
2.  Please check our [contribution guidelines](https://docs.traduora.co/docs/contributing#review-process-for-this-repo) for some help in the process.

chore: bump version

---

.env.sample
.gitignore
api/package.json
api/src/app.module.ts
api/src/config.ts
api/src/env.logger.ts
api/src/main.ts
api/src/services/jwt.strategy.ts
api/src/shutdown.handler.ts
api/src/types.ts

1.  Contributor license agreement
2.  Please check our [contribution guidelines](https://docs.traduora.co/docs/contributing#review-process-for-this-repo) for some help in the process.

[Fix] Critical Privilege Escalation Vulnerability
